### ISSUE TITLE
Hot Campaigns Front-End 

### ISSUE THREAD

**Issue by Kaan2106** [Sonykko/Havana_theallseeingeye#5]
If you haven't setup any "Hot Campaigns" or haven't acivated ones, the front-end looks like this:
![Screenshot 2024-09-08 232451](https://github.com/user-attachments/assets/d3e170b3-a191-4b2c-8d5c-30dc879cc679)

The habblet-container don't get removed it should look like this:
![Screenshot 2024-09-08 232554](https://github.com/user-attachments/assets/1cd14989-e578-4c1f-a786-44644dfc852a)

While at the hot campanins section, there is a missing variable right at the me.tpl file:
`<p class="link"><a href="https://classichabbo.com/credits/club">Go there &raquo;</a></p>`
should be
`<p class="link"><a href="{{ site.sitePath }}/credits/club">Go there &raquo;</a></p>`
I figured out, that the Hot Campaigns should show at least the hc ad, since im not a hc member. But its hidden using 
			</ul>
		</div>
	</div>
</div>
{% endif %}

**Comment by Sonykko** [comment]
Thank's for report, but wrong site to do it, make a PR and I go check if is correct and if the answer is yes, I go to merge the PR. And for the HC Hot Campaing is hidden by Quackster, in other words, it's like Havana from Quackster have published the me.tpl, but than's equalment for report it too :)
