### ISSUE TITLE
Edit Rank results into error message

### ISSUE THREAD

**Issue by Kaan2106** [Sonykko/Havana_theallseeingeye#7]
When renaming a rank, the description seems to be a required condition:
![grafik](https://github.com/user-attachments/assets/c65dafa8-dd35-43f0-b0e0-6f8d6c17668c)

Also can't rename the "Administrador" group even if I filled in the desc:
![grafik](https://github.com/user-attachments/assets/1081b1c4-2291-4376-92a0-5ec03f18122f)

**Comment by Sonykko** [comment]
Thank's for report it! It's fixed in the last update.

Can donwload the latest release here: [https://github.com/Sonykko/Havana_theallseeingeye/releases](https://github.com/Sonykko/Havana_theallseeingeye/releases)
