### ISSUE TITLE
Staff Picks

### ISSUE THREAD

**Issue by SynologyCH** [Sonykko/Havana_theallseeingeye#8]
Hi, I have a problem that when I click on 'Staff Picks' in rooms, it brings up the error page. Do I need to edit anything in the `me.tpl`?"
![fail](https://github.com/user-attachments/assets/e7eeecb8-5e97-40aa-a530-5d5591ee9efa)

**Comment by Sonykko** [comment]
Hey! Nothing is changed in me.tpl. Make sure you add the new StaffPicksRoom.tpl file in habblet folder, cause looks like the server didn't find It.

**Comment by SynologyCH** [comment]
Hey,
I have added it, and also added all data to the Havana server and web :(

![Unbenannt](https://github.com/user-attachments/assets/881c2ed9-e9a0-451a-b72c-97a9a11014b1)

**Comment by Sonykko** [comment]
Ok, looks stranger. Tell me if the .jar files throws any error and what branch and version are you using.

**Comment by SynologyCH** [comment]
I tried it with the one you provided for compilation, and I received an error message
!(https://github.com/user-attachments/assets/0dabcde8-d999-4d5e-8061-46c1f251fc97)

**Comment by Sonykko** [comment]
Okay, I think you are only using the compiled web jar file and not server one cause the files already have the function getStaffPickRooms() from and your scripts are saying that can't find it in your Havana-Server. So check the part of the commit of this function here: [https://github.com/Sonykko/Havana_theallseeingeye/commit/8094f2da6135d0ddfb446ed053342837a57470ae#diff-fcd5243c5805b15fab12618dc03506aeb424e914620f65ff908c0fb37d339cc1](https://github.com/Sonykko/Havana_theallseeingeye/commit/8094f2da6135d0ddfb446ed053342837a57470ae#diff-fcd5243c5805b15fab12618dc03506aeb424e914620f65ff908c0fb37d339cc1)

**Comment by SynologyCH** [comment]
Tried to compile both things from github, still get the same error

**Comment by Sonykko** [comment]
This feature has been tested before publish it and works fine, and when you openned the issue I tested the project on a new VM and works fine too. So you are missing some code. Paste the code of RoomDao.java file from your Havana-Server please.

**Comment by SynologyCH** [comment]
I have now reinstalled everything and it works now. Thank you for your help and patience. :)
